### PR TITLE
Merge back @antmd 's changes

### PR DESCRIPTION
**Pull request by perfaram**

### CODE REVIEW

**Comment by Kentzo** [comment]
@perfaram nice PR!

Have you been able to test it with my fork already?

**Comment by perfaram** [comment]
Actually... please see [my fork](https://github.com/perfaram/F-Script). I merged your master branch into @antmd 's enhancements branch, then into my own master. It works ! So it may actually be easier to merge by master into yours.

**Comment by Kentzo** [comment]
@perfaram Would you mind to make a PR from that fork?

**Comment by perfaram** [comment]
Yup.

**Comment by perfaram** [comment]
See #20

**Pull request closed without merging**
