### PR TITLE
Fixed error for building it on OSX 10.8.4

### PR DESCRIPTION
**Pull request by whatsbcn**

### CODE REVIEW

**Comment by Kentzo** [comment]
@whatsbcn What compiler do you have problems with?

**Comment by whatsbcn** [comment]
Hi @Kentzo, 

sorry for not tell it on the commit message, I'm compiling it with Xcode Version 4.6.3 and the included Apple compiler LLVM 4.2.

## 

 Albert Sellarès        GPG id: 0x13053FFE
 http://www.wekk.net    Linux User: 324456

El 18/08/2013, a les 21:50, Ilya Kulakov notifications@github.com va escriure:

**Comment by Kentzo** [comment]
@whatsbcn What error do you have? I'm asking because I didn't have problems before.

**Comment by whatsbcn** [comment]
@Kentzo The error before my patch is:

Semantic issue
Uknown type name 'typeof'; did you mean the keyword 'typedef'?

**Comment by hamlinmark** [comment]
Thanks for pushing this fix, i had the same problems on on osx 10.8 with Apple LVM Compiler in xcode 4.6. and used the typeof -> **typeof** to get it working.

Mark

**Pull request merged**
